# scripts/lexicon_data_part4.py
# The remaining 74 words to reach 100% full coverage of Juz 'Amma

LEXICON_PART4 = {
    'أَنَّا': 'C’est bien Nous Qui',
    'مِّنْهُمْ': 'd’entre eux',
    'سَوَّىٰهَا': 'l’a façonnée et agencée avec harmonie',
    'ثَمُودُ': 'le peuple de Thamûd',
    'إِذِ': 'lorsque',
    'رَبُّهُم': 'leur Seigneur et Maître',
    'يَعْلَمُ': 'Il sait parfaitement',
    'يَصْلَى': 'il brûlera et sera consumé dans',
    'قَدْ': 'a certes',
    'رَبَّهُم': 'leur Seigneur',
    'ذَا': 'doté de / appartenant à',
    'مُّطَهَّرَةً': 'purifiés de toute souillure',
    'جَآءَتْهُمُ': 'leur fut parvenue',
    'نَارِ': 'le feu ardent de',
    'رَبِّهِمْ': 'leur Seigneur plein de grâce',
    'أَبَدًا': 'à tout jamais pour l’éternité',
    'عَنْهُمْ': 'd’eux avec bienveillance',
    'مِنْهُمْ': 'd’entre eux',
    'يُؤْمِنُوا۟': 'qu’ils aient foi et croient en',
    'كُلِّ': 'toute',
    'ذُو': 'le Détenteur souverain de',
    'قُرْءَانٌ': 'une Récitation coranique',
    'عَذَابٍ': 'un châtiment douloureux',
    'رَبِّىَ': 'mon Seigneur',
    'يَوْمَئِذٍۭ': 'ce jour-là précisément',
    'يَقُولُ': 'il dira avec amertume',
    'يَـٰٓأَيَّتُهَا': 'Ô toi',
    'جَنَّةٍ': 'un Jardin d’éden',
    'عَيْنٌ': 'une source d’eau vive',
    'مَصْفُوفَةٌ': 'disposés en rangées harmonieuses',
    'عَلَيْهِم': 'sur eux en geôlier',
    'نَارُ': 'le Feu attisé de',
    'مُّؤْصَدَةٌ': 'hermétiquement refermé',
    'إِنَّكَ': 'en vérité toi',
    'كِتَـٰبَهُۥ': 'son livre de comptes',
    'أَهْلِهِۦ': 'sa famille bienheureuse',
    'يُؤْمِنُونَ': 'ils ne croient avec sincérité',
    'عَلَيْهِمُ': 'sur eux',
    'رَكَّبَكَ': 'Il t’a constitué et assemblé',
    'دِينِ': 'ma religion et ma foi pure',
    'كَذَّبَ': 'a osé démentir avec orgueil',
    'مَالَهُۥ': 'sa fortune et ses richesses',
    'أَو': 'ou bien',
    'أَنَّهُم': 'qu’ils',
    'سِجِّينٌ': 'Sijjîn (le registre scellé des impies)',
    'كِتَـٰبٌ': 'un livre consigné avec rigueur',
    'يُكَذِّبُونَ': 'ils traitent d’imposture et de mensonge',
    'كُلُّ': 'tout',
    'عَلَيْهِ': 'sur lui',
    'قَالَ': 'il s’écria avec mépris',
    'عَلَىٰ': 'sur',
    'يُقَالُ': 'il leur sera proclamé avec fermeté',
    'هَـٰذَا': 'voici donc',
    'عِلِّيُّونَ': '‘Illiyyûn (les hauts degrés du Paradis)',
    'ٱنقَلَبُوا۟': 'ils s’en retournaient satisfaits',
    'قَالُوٓا۟': 'ils s’écriaient avec ironie',
    'هَـٰٓؤُلَآءِ': 'ceux-là en vérité',
    'عَلَيْهِمْ': 'sur eux comme surveillants',
    'هِيَهْ': 'ce que c’est que cet abîme ?',
    'رَبُّكُمُ': 'votre seigneur suprême',
    'ءَأَنتُمْ': 'seriez-vous donc plus ardus ?',
    'دَحَىٰهَآ': 'Il l’a nivelée et étendue',
    'مَتَـٰعًا': 'comme provision et bienfaisance',
    'سَعَىٰ': 'ce qu’il a œuvré et accompli',
    'أَنتَ': 'toi',
    'ذِكْرَىٰهَآ': 'd’en connaître le secret',
    'مُنتَهَىٰهَآ': 'son terme ultime appartient à Allah',
    'يَرَوْنَهَا': 'ils la contempleront de leurs yeux',
    'قُتِلَتْ': 'elle a été sauvagement tuée',
    'مِنكُمْ': 'd’entre vous',
    'نَفْسٍ': 'une âme humaine',
    'مَمْنُونٍ': 'interrompue ni amoindrie',
    'أَلَيْسَ': 'Allah n’est-Il point donc ?',
    'يَخْشَىٰ': 'craint (la justice d’Allah) avec piété',
}
