# scripts/lexicon_data_part3.py
# Comprehensive, accurate French translations for Quranic vocabulary in Juz 'Amma (Surahs 88 to 114)

LEXICON_PART3 = {
    # Surah 88 Al-Ghachiya
    'ٱلْغَـٰشِيَةِ': 'l’Événement qui enveloppera tout de terreur',
    'عَامِلَةٌ': 'éreintée et peinant sous le fardeau',
    'نَّاصِبَةٌ': 'épuisée et harassée de fatigue',
    'تَصْلَىٰ': 'brûlant dans l’embrasement de',
    'حَامِيَةً': 'ardente et incandescente',
    'تُسْقَىٰ': 'abreuvée de force',
    'عَيْنٍ': 'd’une source d’eau bouillante',
    'ءَانِيَةٍ': 'parvenue au paroxysme de la chaleur',
    'طَعَامٌ': 'la moindre nourriture',
    'ضَرِيعٍ': 'de darî’ (épines vénéneuses fétides)',
    'يُسْمِنُ': 'qui n’engraisse aucunement le corps',
    'يُغْنِى': 'ni ne soulage la faim dévorante',
    'جُوعٍ': 'la moindre faim',
    'نَّاعِمَةٌ': 'comblées de délices et resplendissantes',
    'لِّسَعْيِهَا': 'de leurs efforts consentis sur terre',
    'رَاضِيَةٌ': 'pleinement satisfaites et réjouies',
    'عَالِيَةٍ': 'élevé en degrés et en majesté',
    'لَّا': 'on n’y',
    'تَسْمَعُ': 'entendra jamais',
    'لَـٰغِيَةً': 'la moindre parole vaine ou futile',
    'جَارِيَةٌ': 'qui coule à flots continus',
    'سُرُرٌ': 'des lits de repos royaux',
    'مَّرْفُوعَةٌ': 'surélevés et majestueux',
    'وَأَكْوَابٌ': 'et des coupes étincelantes',
    'مَّوْضُوعَةٌ': 'disposées à portée de main',
    'وَنَمَارِقُ': 'et des coussins somptueux',
    'مَّصْفُوفَةٌ': 'alignés en rangées parfaites',
    'وَزَرَابِىُّ': 'et des tapis soyeux précieux',
    'مَبْثُوثَةٌ': 'déployés et parsemés partout',
    'أَفَلَا': 'Ne vont-ils donc pas observer',
    'يَنظُرُونَ': 'méditer et contempler',
    'ٱلْإِبِلِ': 'les chameaux (al-ibil, miracle d’endurance)',
    'خُلِقَتْ': 'comment ils ont été créés avec ingéniosité',
    'ٱلسَّمَآءِ': 'le ciel majestueux',
    'رُفِعَتْ': 'comment il a été élevé sans piliers',
    'ٱلْجِبَالِ': 'les montagnes massives',
    'نُصِبَتْ': 'comment elles ont été dressées en piquets',
    'ٱلْأَرْضِ': 'la surface terrestre',
    'سُطِحَتْ': 'comment elle a été nivelée et aplanie',
    'مُذَكِّرٌ': 'un rappelant bienveillant',
    'لَّسْتَ': 'tu n’es aucunement',
    'بِمُصَيْطِرٍ': 'un tyran ni geôlier sur leurs cœurs',
    'تَوَلَّىٰ': 'tourne dédaigneusement le dos',
    'وَكَفَرَ': 'et persiste dans sa mécréance',
    'فَيُعَذِّبُهُ': 'le châtiera impitoyablement',
    'ٱلْعَذَابَ': 'du châtiment sans commune mesure',
    'إِلَيْنَآ': 'c’est vers Nous seuls que revient',
    'إِيَابَهُمْ': 'leur retour inéluctable après la mort',
    'عَلَيْنَا': 'il Nous incombe à Nous seuls',
    'حِسَابَهُم': 'de leur demander des comptes stricts',

    # Surah 89 Al-Fajr
    'وَٱلْفَجْرِ': 'Par l’aube naissante qui dissipe la nuit',
    'عَشْرٍ': 'par les dix nuits sacrées (de Dhul-Hijja)',
    'وَٱلشَّفْعِ': 'par le pair régulier',
    'وَٱلْوَتْرِ': 'et par l’impair unique',
    'يَسْرِ': 'quand elle s’écoule et s’en va',
    'قَسَمٌ': 'un serment d’une gravité insigne',
    'لِّذِى': 'pour quiconque possède',
    'حِجْرٍ': 'une raison éclairée et lucide',
    'فَعَلَ': 'a traité souverainement',
    'بِعَادٍ': 'le puissant peuple d’‘Âd',
    'إِرَمَ': 'la cité légendaire d’Iram',
    'ٱلْعِمَادِ': 'aux colonnes et piliers monumentaux',
    'يُخْلَقْ': 'n’avait jamais été édifié de pareil',
    'مِثْلُهَا': 'son semblable grandiose',
    'ٱلْبِلَـٰدِ': 'à travers toutes les contrées',
    'جَابُوا۟': 'ont taillé et creusé la roche',
    'ٱلصَّخْرَ': 'les énormes blocs de pierre',
    'بِٱلْوَادِ': 'au creux de la vallée de Wâdî al-Qurâ',
    'ٱلْأَوْتَادِ': 'aux légions armées et pieux de supplices',
    'طَغَوْا۟': 'ont rivalisé de tyrannie et d’injustice',
    'فَأَكْثَرُوا۟': 'y multipliant sans vergogne',
    'ٱلْفَسَادَ': 'la corruption, le mal et la ruine',
    'فَصَبَّ': 'déversa alors d’en haut',
    'سَوْطَ': 'le fouet cinglant de Son',
    'لَبِٱلْمِرْصَادِ': 'est sans cesse aux aguets, rien ne Lui échappe',
    'ٱبْتَلَىٰهُ': 'le met à l’épreuve par Ses décrets',
    'فَأَكْرَمَهُۥ': 'en le comblant de largesses',
    'وَنَعَّمَهُۥ': 'et en le gratifiant de Ses bienfaits',
    'رَبِّىٓ': 'mon Seigneur plein de grâce',
    'أَكْرَمَنِ': 'm’a personnellement honoré par ce bien !',
    'فَقَدَرَ': 'en restreignant avec mesure',
    'رِزْقَهُۥ': 'sa part de subsistance quotidienne',
    'أَهَـٰنَنِ': 'm’a rabaissé et humilié injustement !',
    'تُكْرِمُونَ': 'vous ne traitez avec générosité',
    'ٱلْيَتِيمَ': 'l’orphelin privé de soutien',
    'تَحَـٰٓضُّونَ': 'vous ne vous encouragez mutuellement à',
    'طَعَامِ': 'nourrir et assister avec cœur',
    'ٱلْمِسْكِينِ': 'le pauvre démuni dans le besoin',
    'تَأْكُلُونَ': 'vous engloutissez avec avidité',
    'ٱلتُّرَاثَ': 'l’héritage sans respecter les droits',
    'أَكْلًا': 'd’un appétit féroce',
    'لَّمًّا': 'dévorant la part des plus faibles',
    'تُحِبُّونَ': 'vous affectionnez avec passion',
    'ٱلْمَالَ': 'les richesses matérielles',
    'حُبًّا': 'd’un amour ardent et démesuré',
    'جَمًّا': 'insatiable et sans limite',
    'دُكَّتِ': 'sera pulvérisée et nivelée',
    'دَكًّا': 'choc après choc et fracas répété',
    'وَجَآءَ': 'que se manifestera l’Ordre suprême de',
    'وَٱلْمَلَكُ': 'et les rangs serrés des anges',
    'صَفًّا': 'déployés en rangées majestueuses',
    'جِا۟ىٓءَ': 'sera amenée devant tous',
    'يَتَذَكَّرُ': 'l’homme prendra enfin pleine conscience',
    'وَأَنَّىٰ': 'mais d’où donc lui servirait',
    'لَهُ': 'à son profit tardif',
    'ٱلذِّكْرَىٰ': 'un tel rappel désormais inutile ?',
    'يَـٰلَيْتَنِى': 'Hélas pour moi ! Si seulement',
    'قَدَّمْتُ': 'j’avais préparé de bonnes œuvres',
    'لِحَيَاتِى': 'pour ma vraie vie éternelle !',
    'يُعَذِّبُ': 'nul ne saurait infliger un châtiment',
    'عَذَابَهُۥٓ': 'semblable à Son châtiment suprême',
    'أَحَدٌ': 'personne au monde',
    'يُوثِقُ': 'nul ne saurait garrotter et lier',
    'وَثَاقَهُۥٓ': 'comme Il enchaîne les coupables',
    'ٱلنَّفْسُ': 'Ô âme paisible',
    'ٱلْمُطْمَئِنَّةُ': 'apaisée dans la foi et la certitude !',
    'ٱرْجِعِىٓ': 'Retourne sereinement',
    'رَاضِيَةً': 'pleinement agréée et satisfaite',
    'مَّرْضِيَّةً': 'trouvant le noble agrément d’Allah',
    'فَٱدْخُلِى': 'Rejoins donc avec honneur',
    'عِبَـٰدِى': 'le cercle de Mes serviteurs pieux',
    'وَٱدْخُلِى': 'et pénètre rayonnante dans',
    'جَنَّتِى': 'Mon Paradis de paix éternelle !',

    # Surah 90 Al-Balad
    'بِهَـٰذَا': 'par cette illustre et sainte cité',
    'ٱلْبَلَدِ': 'de La Mecque (Al-Balad al-Amîn)',
    'حِلٌّۢ': 'toi qui y résides en citoyen libre',
    'وَوَالِدٍ': 'par le père procréateur (Adam ou Abraham)',
    'وَلَدَ': 'et par toute sa descendance humaine',
    'خَلَقْنَا': 'Nous avons façonné et créé',
    'كَبَدٍ': 'dans une épreuve de labeur et d’endurance',
    'أَيَحْسَبُ': 'S’imagine-t-il donc dans son illusion ?',
    'يَقْدِرَ': 'n’aura le moindre pouvoir sur',
    'أَهْلَكْتُ': 'J’ai englouti et dilapidé',
    'مَالًا': 'd’immenses fortunes de richesses',
    'لُّبَدًا': 'entassées en monceaux extravagants !',
    'يَرَهُۥٓ': 'personne ne l’a surveillé ni vu ?',
    'عَيْنَيْنِ': 'deux yeux perçants pour contempler ?',
    'وَلِسَانًا': 'une langue agile pour s’exprimer ?',
    'وَشَفَتَيْنِ': 'deux lèvres pour articuler la parole ?',
    'وَهَدَيْنَـٰهُ': 'et ne l’avons-Nous pas guidé vers',
    'ٱلنَّجْدَيْنِ': 'les deux voies bien distinctes (bien et mal) ?',
    'فَلَا': 'Mais il n’a pas osé franchir',
    'ٱقْتَحَمَ': 's’engager bravement sur',
    'ٱلْعَقَبَةَ': 'la voie montante escarpée de l’effort pieux',
    'فَكُّ': 'l’affranchissement d’un esclave captif',
    'رَقَبَةٍ': 'le rachat d’une vie enchaînée',
    'إِطْعَـٰمٌ': 'le don fraternel de nourriture',
    'مَسْغَبَةٍ': 'au cœur d’une disette et famine cruelle',
    'يَتِيمًا': 'à un orphelin vulnérable',
    'مَقْرَبَةٍ': 'faisant partie de la proche parenté',
    'مِسْكِينًا': 'à un indigent sans ressource',
    'مَتْرَبَةٍ': 'réduit à coucher dans la poussière de dénuement',
    'تَوَاصَوْا۟': 'qui se sont mutuellement recommandé',
    'بِٱلصَّبْرِ': 'la persévérance inébranlable et l’endurance',
    'بِٱلْمَرْحَمَةِ': 'la compassion bienveillante et l’amour d’autrui',
    'ٱلْمَيْمَنَةِ': 'de la Droite (les élus reçus au Paradis)',
    'ٱلْمَشْـَٔمَةِ': 'de la Gauche (les réprouvés de l’Enfer)',
    'مُّؤْصَدَةٌۢ': 'inexorablement close et hermétiquement scellée',

    # Surah 91 Ach-Chams & 92 Al-Layl
    'وَٱلشَّمْسِ': 'Par le soleil rayonnant de vie',
    'تَلَىٰهَا': 'par la lune quand elle lui succède fidèlement',
    'جَلَّىٰهَا': 'par le jour quand il en révèle tout l’éclat',
    'يَغْشَىٰهَا': 'par la nuit quand elle l’enveloppe d’ombre',
    'طَحَىٰهَا': 'par la terre et la façon dont Il l’a étendue',
    'وَنَفْسٍ': 'par l’âme humaine et sa conscience',
    'فَأَلْهَمَهَا': 'et Il lui a inspiré le discernement entre',
    'فُجُورَهَا': 'sa propension au mal et à la perversion',
    'وَتَقْوَىٰهَا': 'et sa ferveur vers la piété vertueuse',
    'زَكَّىٰهَا': 'quiconque purifie son âme de tout vice',
    'خَابَ': 'a couru à sa perte et a échoué',
    'دَسَّىٰهَا': 'quiconque l’étouffe et la souille dans le péché',
    'كَذَّبَتْ': 'a crié au mensonge par son insolence',
    'بِطَغْوَىٰهَآ': 'par son égarement outrancier et rebelle',
    'ٱنۢبَعَثَ': 'lorsque s’élança en fureur criminelle',
    'أَشْقَىٰهَا': 'le plus félon et scélérat de ses hommes',
    'فَقَالَ': 'leur dit alors solennellement',
    'رَسُولُ': 'l’illustre messager d’Allah (Salih)',
    'نَاقَةَ': 'Prenez garde à la chamelle miraculeuse d’Allah !',
    'وَسُقْيَـٰهَا': 'et ne l’empêchez point de boire à son tour !',
    'فَعَقَرُوهَا': 'mais ils l’égorgèrent avec impiété',
    'فَدَمْدَمَ': 's’abattit alors sur eux Son courroux destructeur',
    'بِذَنۢبِهِمْ': 'en punition de leur crime sacrilège',
    'فَسَوَّىٰهَا': 'les anéantissant tous d’un coup égal',
    'يَخَافُ': 'sans craindre aucune représaille de quiconque',
    'عُقْبَـٰهَا': 'des suites de cet anéantissement',

    # Surah 92 Al-Layl & 93 Ad-Duha
    'يَغْشَىٰ': 'quand elle déploie son manteau d’obscurité',
    'تَجَلَّىٰ': 'quand il resplendit de lumière souveraine',
    'ٱلذَّكَرَ': 'le mâle robuste',
    'وَٱلْأُنثَىٰٓ': 'et la femelle délicate',
    'سَعْيَكُمْ': 'vos efforts et quêtes quotidiennes',
    'لَشَتَّىٰ': 'divergent profondément en buts et finalités',
    'أَعْطَىٰ': 'a donné avec générosité de ses biens',
    'وَٱتَّقَىٰ': 'et s’est prémuni par la crainte pieuse',
    'وَصَدَّقَ': 'et a cru de tout son être à',
    'بِٱلْحُسْنَىٰ': 'la plus sublime promesse de félicité',
    'فَسَنُيَسِّرُهُۥ': 'Nous lui aplanirons la voie douce vers',
    'لِلْيُسْرَىٰ': 'la félicité céleste et l’aisance spirituelle',
    'بَخِلَ': 's’est montré avare et cupide',
    'وَٱسْتَغْنَىٰ': 'et a prétendu se suffire à lui-même',
    'وَكَذَّبَ': 'et a rejeté avec dédain',
    'لِلْعُسْرَىٰ': 'la voie pénible du malheur et de la ruine',
    'مَالُهُۥٓ': 'ses richesses ammassées avec fièvre',
    'تَرَدَّىٰٓ': 'lorsqu’il basculera dans le gouffre de la tombe',
    'لَلْهُدَىٰ': 'de dispenser la juste guidance aux cœurs',
    'وَإِنَّ': 'et à Nous appartiennent en souveraineté',
    'لَلْأٓخِرَةَ': 'le royaume de l’Au-delà éternel',
    'وَٱلْأُولَىٰ': 'et la demeure de la vie terrestre première',
    'فَأَنذَرْتُكُمْ': 'Je vous ai donc mis solennellement en garde contre',
    'تَلَظَّىٰ': 'un Feu furieux qui crépite et dévore',
    'يَصْلَىٰهَآ': 'n’y sera consumé que',
    'ٱلْأَشْقَى': 'le plus misérable et endurci des ingrats',
    'سَيُجَنَّبُهَا': 'en sera préservé à jamais',
    'ٱلْأَتْقَى': 'le croyant le plus pur et empli de dévotion',
    'يُؤْتِى': 'dépense de sa fortune acquise',
    'يَتَزَكَّىٰ': 'pour purifier son cœur et non pour briller',
    'لِأَحَدٍ': 'envers qui que ce soit',
    'عِندَهُۥ': 'auprès de lui',
    'نِّعْمَةٍ': 'une faveur personnelle reçue jadis',
    'تُجْزَىٰٓ': 'qui mériterait d’être compensée',
    'ٱبْتِغَآءَ': 'uniquement par désir sincère de contempler',
    'وَجْهِ': 'la noble Face auguste de',
    'وَلَسَوْفَ': 'et il sera très certainement',
    'يَرْضَىٰ': 'pleinement comblé et émerveillé',

    # Surah 93 Ad-Duha & 94 Al-Inchirah & 95 At-Tin
    'وَٱلضُّحَىٰ': 'Par la clarté éclatante de la matinée naissante',
    'سَجَىٰ': 'quand elle s’apaise et étend son calme paisible',
    'وَدَّعَكَ': 'ne t’a point délaissé ni abandonné',
    'قَلَىٰ': 'ni n’a éprouvé la moindre aversion envers toi',
    'يُعْطِيكَ': 'te comblera de Ses bienfaits sublimes',
    'فَتَرْضَىٰٓ': 'de sorte que tu seras comblé d’agrément',
    'يَجِدْكَ': 'ne t’a-t-Il pas trouvé',
    'يَتِيمًا': 'orphelin solitaire sans protecteur',
    'فَـَٔاوَىٰ': 'puis t’a accordé un noble gîte et soutien ?',
    'وَوَجَدَكَ': 'ne t’a-t-Il pas trouvé en quête',
    'ضَآلًّا': 'ignorant des détails de la Révélation',
    'فَهَدَىٰ': 'puis t’a guidé vers la lumière divine ?',
    'عَآئِلًا': 'démuni de biens temporels',
    'فَأَغْنَىٰ': 'puis t’a enrichi de sagesse et de suffisance ?',
    'فَلَا': 'ne va surtout pas',
    'تَقْهَرْ': 'le rudoyer ni froisser sa dignité',
    'ٱلسَّآئِلَ': 'le mendiant ou demandeur de savoir',
    'تَنْهَرْ': 'le repousser avec rudesse ou dédain',
    'بِنِعْمَةِ': 'quant aux bienfaits infinis reçus de',
    'فَحَدِّثْ': 'raconte-les avec reconnaissance et ferveur !',

    # Surah 94 Al-Inchirah & 95 At-Tin
    'نَشْرَحْ': 'n’avons-Nous pas ouvert et apaisé pour toi',
    'صَدْرَكَ': 'ta poitrine pour accueillir la paix et la foi ?',
    'وَوَضَعْنَا': 'et ne t’avons-Nous pas déchargé de',
    'وِزْرَكَ': 'ton lourd fardeau d’angoisse spirituelle',
    'أَنقَضَ': 'qui pesait si lourdement sur',
    'ظَهْرَكَ': 'ton dos meurtri ?',
    'وَرَفَعْنَا': 'et Nous avons élevé au plus haut',
    'ذِكْرَكَ': 'ton nom et ton souvenir digne d’éloge',
    'ٱلْعُسْرِ': 'la rigueur de la difficulté',
    'يُسْرًا': 'une délivrance et une aisance certaine',
    'فَرَغْتَ': 'tu as terminé tes obligations',
    'فَٱنصَبْ': 'consacre-toi à la prière avec ferveur !',
    'فَٱرْغَب': 'adresse avec ardeur toutes tes espérances !',

    # Surah 95 At-Tin
    'وَٱلتِّينِ': 'Par la figue douce et bénie',
    'وَٱلزَّيْتُونِ': 'et par l’olive généreuse en lumière',
    'وَطُورِ': 'et par le Mont sacré du Sinaï',
    'سِينِينَ': 'de la Révélation donnée à Moïse',
    'ٱلْأَمِينِ': 'sûr, préservé et inviolable (La Mecque)',
    'أَحْسَنِ': 'la plus noble et harmonieuse',
    'تَقْوِيمٍ': 'stature et perfection de forme',
    'رَدَدْنَـٰهُ': 'Nous l’avons ramené au plus bas',
    'أَسْفَلَ': 'au degré le plus vil et déchu',
    'سَـٰفِلِينَ': 'parmi les créatures avilies par le péché',
    'فَلَهُمْ': 'ils recevront en partage',
    'أَجْرٌ': 'une récompense sans fin',
    'يُكَذِّبُكَ': 'te pousse à démentir effrontément',
    'بِأَحْكَمِ': 'le plus sage et juste',
    'ٱلْحَـٰكِمِينَ': 'parmi tous les juges suprêmes ?',

    # Surah 96 Al-Alaq & 97 Al-Qadr
    'ٱقْرَأْ': 'Lis et récite au Nom de',
    'بِٱسْمِ': 'par le Nom auguste de',
    'عَلَقٍ': 'd’une adhérence accrochée à la matrice',
    'ٱلْأَكْرَمُ': 'le Plus Noble et Munificent',
    'عَلَّمَ': 'a enseigné le savoir universel',
    'بِٱلْقَلَمِ': 'par l’usage du Calame (la plume)',
    'يَعْلَمْ': 'ce qu’il ignorait totalement',
    'كَلَّآ': 'Prenez garde ! En vérité',
    'لَيَطْغَىٰٓ': 'dépasse toute mesure d’arrogance',
    'رَّءَاهُ': 'dès qu’il se perçoit',
    'ٱسْتَغْنَىٰٓ': 'autosuffisant et plein de richesses',
    'ٱلرُّجْعَىٰٓ': 'le retour ultime pour le Jugement',
    'أَرَءَيْتَ': 'As-tu vu ce négateur effronté',
    'يَنْهَىٰ': 'qui interdit et empêche',
    'عَبْدًا': 'un humble serviteur d’Allah (le Prophète)',
    'صَلَّىٰٓ': 'd’accomplir la prière devant Dieu ?',
    'ٱلْهُدَىٰٓ': 'sur la voie de la juste guidance ?',
    'أَمَرَ': 'ou s’il prescrivait avec sincérité',
    'بِٱلتَّقْوَىٰٓ': 'la piété et la conscience d’Allah ?',
    'أَلَمْ': 'Ne sait-il donc pas encore',
    'يَعْلَم': 'avec certitude',
    'يَرَىٰ': 'observe chacun de ses agissements ?',
    'يَنتَهِ': 's’il ne met pas fin à son insolence',
    'لَنَسْفَعًۢا': 'Nous le saisirons violemment',
    'بِٱلنَّاصِيَةِ': 'par le toupet du front (le front coupable)',
    'نَاصِيَةٍ': 'un toupet arrogant',
    'كَـٰذِبَةٍ': 'menteur et obstiné dans l’égarement',
    'خَاطِئَةٍ': 'enraciné dans le péché et la transgression',
    'فَلْيَدْعُ': 'Qu’il appelle donc à son secours',
    'نَادِيَهُۥ': 'son assemblée de complices et de guerriers !',
    'سَنَدْعُ': 'Nous appellerons aussitôt',
    'ٱلزَّبَانِيَةَ': 'les gardiens angéliques de l’Enfer impitoyables !',
    'تُطِعْهُ': 'ne lui obéis en rien !',
    'وَٱسْجُدْ': 'mais prosterne-toi avec humilité',
    'وَٱقْتَرِب': 'et rapproche-toi de ton Seigneur béni !',

    # Surah 97 Al-Qadr & 98 Al-Bayyina
    'أَنزَلْنَـٰهُ': 'Nous l’avons fait descendre (le Coran)',
    'لَيْلَةِ': 'durant la nuit bénie de',
    'ٱلْقَدْرِ': 'la Destinée et du Décret divin',
    'أَلْفِ': 'mille mois de dévotion humaine',
    'شَهْرٍ': 'mois terrestres ordinaires',
    'تَنَزَّلُ': 'descendent en vagues de bénédictions',
    'ٱلْمَلَـٰٓئِكَةُ': 'les légions angéliques saintes',
    'وَٱلرُّوحُ': 'et l’Esprit sublime (l’ange Jibril)',
    'بِإِذْنِ': 'par la noble permission de',
    'رَبِّهِم': 'leur Seigneur et Maître',
    'أَمْرٍ': 'toute affaire et décret ordonné',
    'سَلَـٰمٌ': 'Elle est paix, sérénité et salut purs',
    'مَطْلَعِ': 'jusqu’au lever étincelant de',
    'ٱلْفَجْرِ': 'l’aube naissante du jour',

    # Surah 98 Al-Bayyina & 99 Az-Zalzala
    'كَفَرُوا۟': 'ont mécru et persisté dans le rejet',
    'أَهْلِ': 'parmi les gens détenteurs de',
    'ٱلْكِتَـٰبِ': 'l’Écriture révélée (Thora et Évangile)',
    'وَٱلْمُشْرِكِينَ': 'et les polythéistes idolâtres',
    'مُنفَكِّينَ': 'ne pouvaient abandonner leurs croyances',
    'تَأْتِيَهُمُ': 'jusqu’à ce que leur vienne',
    'ٱلْبَيِّنَةُ': 'la Preuve évidente et éclatante',
    'رَسُولٌ': 'un Messager pur envoyé par Allah',
    'يَتْلُوا۟': 'qui leur récite des feuillets sacrés',
    'صُحُفًا': 'des Écritures saintes sublimes',
    'فِيهَا': 'contenant en leur sein',
    'كُتُبٌ': 'des préceptes et enseignements écrits',
    'قَيِّمَةٌ': 'd’une rectitude et justesse parfaites',
    'تَفَرَّقَ': 'ne se sont divisés en sectes rivales',
    'أُوتُوا۟': 'qui avaient reçu les Livres saints',
    'إِلَّا': 'qu’après que',
    'أُمِرُوٓا۟': 'ils n’avaient pourtant reçu d’autre ordre que',
    'لِيَعْبُدُوا۟': 'd’adorer et servir loyalement',
    'مُخْلِصِينَ': 'en Lui vouant un culte exclusif et pur',
    'حُنَفَآءَ': 'monothéistes sincères rejetant le polythéisme',
    'وَيُقِيمُوا۟': 'd’accomplir fidèlement',
    'ٱلصَّلَوٰةَ': 'la prière rituelle quotidienne',
    'وَيُؤْتُوا۟': 'et d’acquitter l’aumône purificatrice de',
    'ٱلزَّكَوٰةَ': 'la Zakât envers les nécessiteux',
    'دِينُ': 'la religion et la voie d’une rectitude',
    'ٱلْقَيِّمَةِ': 'inestimable et inébranlable',
    'خَـٰلِدِينَ': 'demeurant pour l’éternité',
    'شَرُّ': 'les pires créatures parmi',
    'ٱلْبَرِيَّةِ': 'toutes les créatures de l’univers',
    'ٱلصَّـٰلِحَـٰتِ': 'et ont accompli des œuvres vertueuses',
    'خَيْرُ': 'les plus nobles et meilleures créatures',
    'جَزَآؤُهُمْ': 'Leur rétribution suprême',
    'جَنَّـٰتُ': 'les Jardins d’Éden éternels de',
    'عَدْنٍ': 'séjour permanent et inviolé',
    'رَّضِىَ': 'Allah a agréé avec amour',
    'رَضُوا۟': 'et ils ont agréé avec allégresse',
    'عَنْهُ': 'Ses dons et Sa grâce infinie',
    'خَشِىَ': 'quiconque aura craint et vénéré',

    # Surah 99 Az-Zalzala & 100 Al-Adiyat
    'زُلْزِلَتِ': 'sera secouée et ébranlée avec force',
    'ٱلْأَرْضُ': 'la terre entière',
    'زِلْزَالَهَا': 'de son ultime et violent tremblement',
    'وَأَخْرَجَتِ': 'et qu’elle aura expulsé et rejeté au dehors',
    'أَثْقَالَهَا': 'tous ses lourds fardeaux (trésors et défunts)',
    'وَقَالَ': 'et que s’écriera avec effroi',
    'تُحَدِّثُ': 'elle proclamera et révélera au grand jour',
    'أَخْبَارَهَا': 'tous ses récits et événements passés',
    'بِأَنَّ': 'parce que',
    'أَوْحَىٰ': 'lui aura formellement ordonné et inspiré',
    'يَصْدُرُ': 'surgiront en vagues tumultueuses',
    'أَشْتَاتًا': 'en groupes dispersés et séparés',
    'لِّيُرَوْا۟': 'afin qu’on leur montre les fruits de',
    'أَعْمَـٰلَهُمْ': 'toutes leurs actions accomplies jadis',
    'فَمَن': 'Quiconque alors',
    'يَعْمَلْ': 'aura fait sur terre',
    'مِثْقَالَ': 'le poids minuscule de',
    'ذَرَّةٍ': 'un atome ou grain de poussière',
    'خَيْرًا': 'de bien et de vertu',
    'يَرَهُۥ': 'en contemplera la noble rétribution',
    'شَرًّا': 'de mal ou d’injustice',
    'يَرَهُۥ': 'en verra la juste sanction',

    # Surah 100 Al-Adiyat
    'وَٱلْعَـٰدِيَـٰتِ': 'Par les coursiers galopant avec fougue',
    'ضَبْحًا': 'en soufflant et haletant avec ardeur',
    'فَٱلْمُورِيَـٰتِ': 'par les montures qui font jaillir',
    'قَدْحًا': 'des gerbes d’étincelles sous leurs sabots',
    'فَٱلْمُغِيرَٰتِ': 'par les cavaleries qui fondent sur l’ennemi',
    'صُبْحًا': 'dès les premières lueurs de l’aube',
    'فَأَثَرْنَ': 'soulevant dans leur charge héroïque',
    'نَقْعًا': 'un nuage dense de poussière tourbillonnante',
    'فَوَسَطْنَ': 'qui pénètrent alors au cœur même de',
    'جَمْعًا': 'la masse compacte des ennemis',
    'لِرَبِّهِۦ': 'envers son Bienfaiteur suprême',
    'لَكَنُودٌ': 'est profondément ingrat et oublieux',
    'لَشَهِيدٌ': 'en est lui-même témoin manifeste',
    'لِحُبِّ': 'par amour passionné de',
    'ٱلْخَيْرِ': 'la fortune et des biens matériels',
    'لَشَدِيدٌ': 'est d’une avidité vorace et opiniâtre',
    'أَفَلَا': 'Ne sait-il donc pas ce qui adviendra',
    'بُعْثِرَ': 'quand seront exhumés et dispersés',
    'ٱلْقُبُورِ': 'ce que renferment les profondeurs des tombes',
    'حُصِّلَ': 'et que seront mis à nu et extraits',
    'ٱلصُّدُورِ': 'les secrets les plus intimes des cœurs ?',
    'خَبِيرٌۢ': 'est sur eux parfaitement Informé et Connaisseur',

    # Surah 101 Al-Qari'a & 102 At-Takathur
    'ٱلْقَارِعَةُ': 'Le Fracas qui fracasse les cœurs d’effroi',
    'يَكُونُ': 'les êtres humains seront devenus',
    'كَٱلْفَرَاشِ': 'pareils à une nuée de papillons éparpillés',
    'ٱلْمَبْثُوثِ': 'affolés et volant dans toutes les directions',
    'وَتَكُونُ': 'et les montagnes massives deviendront',
    'كَٱلْعِهْنِ': 'semblables à de la laine cardée et effilochée',
    'ٱلْمَنفُوشِ': 'emportée au gré du vent',
    'فَأَمَّا': 'Quant à celui',
    'ثَقُلَتْ': 'auront du poids sur le plateau',
    'مَوَٰزِينُهُۥ': 'ses balances d’œuvres vertueuses',
    'عِيشَةٍ': 'une vie sublime et comblée de délices',
    'رَّاضِيَةٍ': 'pleinement heureuse et agréable',
    'خَفَّتْ': 'auront été légères et sans substance',
    'فَأُمُّهُۥ': 'sa demeure et son asile maternel sera',
    'هَاوِيَةٌ': 'un Gouffre béant insondable',
    'مَا': 'ce que c’est ?',
    'نَارٌ': 'C’est un Feu ardent',
    'حَامِيَةٌۢ': 'incandescent et dévorant !',

    # Surah 102 At-Takathur
    'أَلْهَىٰكُمُ': 'Vous a distraits et détournés de l’essentiel',
    'ٱلتَّكَاثُرُ': 'la course effrénée aux richesses et au prestige',
    'حَتَّىٰ': 'jusqu’au moment fatal où',
    'زُرْتُمُ': 'vous avez visité et rejoint l’intérieur de',
    'ٱلْمَقَابِرَ': 'vos tombes sans retour',
    'سَوْفَ': 'vous allez bientôt',
    'تَعْلَمُونَ': 'savoir avec une implacable lucidité',
    'عِلْمَ': 'de la certitude absolue de la science',
    'ٱلْيَقِينِ': 'la vérité irréfutable',
    'لَتَرَوُنَّ': 'vous contemplerez assurément de vos yeux',
    'ٱلْجَحِيمَ': 'la Fournaise béante',
    'عَيْنَ': 'avec l’œil même et la vue de',
    'لَتُسْـَٔلُنَّ': 'vous serez très certainement interrogés',
    'ٱلنَّعِيمِ': 'tout bienfait et grâce dont vous jouissiez',

    # Surah 103 Al-Asr
    'خُسْرٍ': 'la perdition, l’illusion et la ruine totale',

    # Surah 104 Al-Humaza & 105 Al-Fil
    'هُمَزَةٍ': 'tout médisant perfide qui diffame dans le dos',
    'لُّمَزَةٍ': 'qui blesse autrui par ses regards et mimiques',
    'جَمَعَ': 'qui a amassé des fortunes colossales',
    'مَالًا': 'des monceaux d’or et de richesses',
    'وَعَدَّدَهُۥ': 'et passe ses jours à les compter avec avarice',
    'يَحْسَبُ': 's’imaginant dans sa folie',
    'أَنَّ': 'que',
    'مَالَهُۥٓ': 'ses richesses amassées',
    'أَخْلَدَهُۥ': 'vont le rendre immortel et éternel !',
    'لَيُنۢبَذَنَّ': 'il sera très certainement précipité sans pitié',
    'ٱلْحُطَمَةِ': 'dans la Broyeuse dévoreuse d’âmes',
    'ٱلْمُوقَدَةُ': 'attisé et allumé par la justice divine',
    'تَطَّلِعُ': 'qui monte et pénètre directement jusqu’au cœur',
    'ٱلْأَفْـِٔدَةِ': 'des cœurs orgueilleux pour les consumer',
    'عَمَدٍ': 'de gigantesques colonnes embrasées',
    'مُّمَدَّدَةٍۭ': 'prolongées et refermées sur eux',

    # Surah 105 Al-Fil & 106 Quraych
    'تَرَ': 'n’as-tu donc pas vu et médité',
    'كَيْفَ': 'comment ton Seigneur Tout-Puissant a châtié',
    'بِأَصْحَـٰبِ': 'les assaillants impies de l’armée de',
    'ٱلْفِيلِ': 'l’Éléphant qui voulaient détruire la Kaaba ?',
    'يَجْعَلْ': 'N’a-t-Il pas réduit à néant',
    'كَيْدَهُمْ': 'leur ruse et complot sacrilège',
    'تَضْلِيلٍ': 'en déroute et perte absolue ?',
    'وَأَرْسَلَ': 'Et Il envoya fondre sur eux d’en haut',
    'طَيْرًا': 'des nuées d’oiseaux de proie',
    'أَبَابِيلَ': 'en escadrilles serrées innombrables',
    'تَرْمِيهِم': 'les criblant de projectiles mortels',
    'بِحِجَارَةٍ': 'de pierres d’argile cuite',
    'سِجِّيلٍ': 'durcies et brûlantes comme le feu',
    'فَجَعَلَهُمْ': 'les réduisant en un instant',
    'كَعَصْفٍ': 'comme de la paille hachée et dévorée',
    'مَّأْكُولٍۭ': 'mâchée et piétinée par le bétail !',

    # Surah 106 Quraych
    'قُرَيْشٍ': 'la tribu de Qoraych gardienne du sanctuaire',
    'إِۦلَـٰفِهِمْ': 'pour leur habitude et sécurité accordée',
    'رِحْلَةَ': 'lors de leur grande caravane commerciale',
    'ٱلشِّتَآءِ': 'd’hiver vers le Yémen opulent',
    'وَٱلصَّيْفِ': 'et d’été vers le Shâm prospère',
    'فَلْيَعْبُدُوا۟': 'Qu’ils adorent donc avec sincérité et amour',
    'ٱلْبَيْتِ': 'cette Maison sacrée de la Kaaba !',
    'أَطْعَمَهُم': 'qui les a nourris et préservés au cœur de',
    'جُوعٍ': 'la famine du désert aride',
    'وَءَامَنَهُم': 'et les a protégés et mis en sécurité',
    'خَوْفٍۭ': 'de la peur et des razzias ennemies !',

    # Surah 107 Al-Ma'un
    'يَدُعُّ': 'repousse violemment avec mépris',
    'يَحُضُّ': 'n’incite ni n’encourage autrui à',
    'صَلَاتِهِمْ': 'leur prière rituelle solennelle',
    'سَاهُونَ': 'distraits, négligents et indifférents',
    'يُرَآءُونَ': 'n’agissent que par pure ostentation pour être vus',
    'وَيَمْنَعُونَ': 'et refusent de prêter la moindre entraide',
    'ٱلْمَاعُونَ': 'le moindre ustensile de secours quotidien !',

    # Surah 109 Al-Kafirun
    'قُلْ': 'Dis solennellement aux négateurs :',
    'ٱلْكَـٰفِرُونَ': 'Ô vous les mécréants obstinés !',
    'أَعْبُدُ': 'Je n’adorerai jamais',
    'تَعْبُدُونَ': 'ce que vous adorez comme idoles',
    'أَنتُمْ': 'vous n’êtes prêts à adorer',
    'عَـٰبِدُونَ': 'ceux qui adorent avec dévotion',
    'عَابِدٌ': 'un adorateur asservi à',
    'عَبَدتُّمْ': 'ce que vous avez toujours adoré',
    'دِينُكُمْ': 'À vous votre fausse religion d’idoles',
    'وَلِىَ': 'et à moi ma foi pure et mon culte exclusif !',

    # Surah 110 An-Nasr
    'جَآءَ': 'arrivera triomphalement',
    'نَصْرُ': 'le secours décisif et la victoire accordée par',
    'وَرَأَيْتَ': 'et que tu verras de tes yeux émus',
    'يَدْخُلُونَ': 'entrer par foules innombrables',
    'أَفْوَاجًا': 'en vagues ardentes de foi sincère',
    'فَسَبِّحْ': 'alors glorifie avec humilité et louange',
    'بِحَمْدِ': 'en célébrant la gloire infinie de',
    'وَٱسْتَغْفِرْهُ': 'et implore Son pardon miséricordieux',
    'تَوَّابًۢا': 'accueille sans cesse le repentir des cœurs !',

    # Surah 111 Al-Masad
    'تَبَّتْ': 'Périssent à jamais dans la ruine',
    'يَدَآ': 'les deux mains sacrilèges de',
    'أَبِى': 'd’Abû Lahab l’ennemi de la vérité',
    'لَهَبٍ': 'au visage enflammé de haine',
    'وَتَبَّ': 'et que lui-même soit voué à l’anéantissement !',
    'أَغْنَىٰ': 'ne lui ont été d’aucun secours salutaire',
    'مَالُهُۥ': 'ses richesses accumulées',
    'كَسَبَ': 'ce qu’il a amassé et comploté',
    'سَيَصْلَىٰ': 'Il sera précipité pour brûler vif dans',
    'نَارًا': 'un Feu ardent aux flammes jaillissantes',
    'ذَاتَ': 'doté d’un embrasement féroce',
    'لَهَبٍ': 'de flammes crépitantes dévorantes',
    'وَٱمْرَأَتُهُۥ': 'ainsi que sa femme haineuse complice',
    'حَمَّالَةَ': 'porteuse d’épines et de calomnies',
    'ٱلْحَطَبِ': 'du bois inflammable de la discorde',
    'جِيدِهَا': 'autour de son cou flétri sera attachée',
    'حَبْلٌ': 'une corde rugueuse et étouffante',
    'مَّسَدٍۭ': 'tressée de fibres rugueuses de palmier !',
}
