# scripts/lexicon_data_part1.py
# Comprehensive, accurate French translations for Quranic vocabulary in Juz 'Amma

LEXICON_PART1 = {
    # Surah 78 An-Naba & Surah 79 An-Nazi'at
    'كِذَّٰبًا': 'd’un démenti absolu / de mensonges',
    'غَرْقًا': 'violemment / en plongeant au fond',
    'نَشْطًا': 'avec douceur et aisance',
    'سَبْحًا': 'en voguant / flottant librement',
    'سَبْقًا': 'avec rapidité / en devançant',
    'أَمْرًا': 'les décrets / les ordres divins',
    'تَرْجُفُ': 'tremblera violemment (premier souffle)',
    'تَتْبَعُهَا': 'la suivra (second souffle)',
    'قُلُوبٌ': 'des cœurs',
    'يَوْمَئِذٍ': 'ce jour-là',
    'أَبْصَـٰرُهَا': 'leurs regards',
    'خَـٰشِعَةٌ': 'baissés d’effroi et d’humiliation',
    'يَقُولُونَ': 'ils disent avec ironie',
    'أَءِنَّا': 'serons-nous donc ?',
    'أَءِذَا': 'est-ce lorsque ?',
    'كُنَّا': 'nous serons devenus',
    'عِظَـٰمًا': 'des ossements',
    'نَّخِرَةً': 'cariés, effrités et réduits en poussière',
    'قَالُوا۟': 'ils disent',
    'تِلْكَ': 'ce serait là',
    'كَرَّةٌ': 'un retour à la vie',
    'خَاسِرَةٌ': 'ruineux et voué à la perte',
    'هِىَ': 'elle / ce ne sera',
    'زَجْرَةٌ': 'un cri / grondement sonore unique',
    'هَلْ': 'est-ce que ?',
    'أَتَىٰكَ': 't’est-il parvenu ?',
    'حَدِيثُ': 'le récit / l’histoire édifiante',
    'مُوسَىٰٓ': 'de Moïse (Moussa)',
    'إِذْ': 'lorsque / quand',
    'نَادَىٰهُ': 'l’appela avec majesté',
    'طُوًى': 'de Touwa (la vallée sacrée du Sinaï)',
    'ٱذْهَبْ': 'va sans tarder !',
    'إِنَّهُۥ': 'car certes il',
    'طَغَىٰ': 'a transgressé toute mesure',
    'هَل': 'as-tu le désir ?',
    'أَن': 'de',
    'تَزَكَّىٰ': 'te purifier de l’arrogance et mécréance ?',
    'أَدْبَرَ': 'tourna le dos avec dédain',
    'يَسْعَىٰ': 's’empressant à comploter',
    'أَنَا۠': 'je suis',
    'أَخَذَهُ': 'le saisit par le châtiment',
    'نَكَالَ': 'comme châtiment exemplaire',
    'ٱلْأٓخِرَةِ': 'de l’Au-delà',
    'عِبْرَةً': 'une grande leçon édifiante',
    'لِّمَن': 'pour quiconque',
    'يَخْشَىٰٓ': 'craint la justice divine',
    'أَءَنتُمْ': 'seriez-vous donc ?',
    'أَشَدُّ': 'plus difficiles et ardus',
    'خَلْقًا': 'à créer',
    'أَمِ': 'ou bien',
    'بَنَىٰهَا': 'qu’Il a édifiée majestueusement',
    'رَفَعَ': 'Il a élevé',
    'سَمْكَهَا': 'sa voûte céleste immense',
    'فَسَوَّىٰهَا': 'et l’a agencée avec harmonie',
    'وَأَغْطَشَ': 'et Il a assombri',
    'لَيْلَهَا': 'sa nuit ténébreuse',
    'وَأَخْرَجَ': 'et a fait jaillir',
    'ضُحَىٰهَا': 'sa vive clarté matinale',
    'دَحَىٰهَا': 'Il l’a étendue et aplanie',
    'أَخْرَجَ': 'Il a fait sourdre et émerger',
    'مِنْهَا': 'd’elle',
    'مَآءَهَا': 'ses eaux jaillissantes',
    'وَمَرْعَىٰهَا': 'et ses pâturages verdoyants',
    'أَرْسَىٰهَا': 'Il les a ancrées solidement',
    'مَّتَـٰعًا': 'comme jouissance et provision',
    'لَّكُمْ': 'pour vous',
    'وَلِأَنْعَـٰمِكُمْ': 'et pour vos troupeaux',
    'جَآءَتِ': 'arrivera inéluctablement',
    'ٱلطَّآمَّةُ': 'le grand Cataclysme écrasant',
    'ٱلْكُبْرَىٰ': 'le Suprême, submergeant tout',
    'يَتَذَكَّرُ': 'se souviendra avec lucidité',
    'مَا': 'de ce que',
    'بُرِّزَتِ': 'sera exposée de manière visible',
    'ٱلْجَحِيمُ': 'la Fournaise ardente',
    'لِمَن': 'pour quiconque',
    'يَرَىٰ': 'peut regarder',
    'ءَاثَرَ': 'a préféré avec avidité',
    'ٱلْحَيَوٰةَ': 'la vie présente éphémère',
    'ٱلدُّنْيَا': 'ici-bas',
    'مَأْوَىٰ': 'le refuge et demeure finale',
    'خَافَ': 'aura redouté avec piété',
    'مَقَامَ': 'la comparution devant',
    'وَنَهَى': 'et aura préservé et retenu',
    'ٱلنَّفْسَ': 'son âme et son ego',
    'عَنِ': 'de',
    'ٱلْهَوَىٰ': 'la passion et des désirs bas',
    'ٱلْمَأْوَىٰ': 'le séjour et demeure éternelle',
    'يَسْـَٔلُونَكَ': 'ils t’interrogent avec insistance',
    'عَنِ': 'au sujet de',
    'ٱلسَّاعَةِ': 'l’Heure du Jugement',
    'أَيَّانَ': 'quand adviendra',
    'مُرْسَىٰهَا': 'son terme et son avènement ?',
    'فِيمَ': 'en quoi es-tu concerné ?',
    'ذِكْرَىٰهَا': 'd’en divulguer l’instant précis ?',
    'مُنتَهَىٰهَا': 'appartient la connaissance ultime de son terme',
    'إِنَّمَآ': 'tu n’es en vérité que',
    'مُنذِرُ': 'un avertisseur bienveillant',
    'يَخْشَىٰهَا': 'la redoute avec piété',
    'كَأَنَّهُمْ': 'comme s’ils',
    'لَمْ': 'n’avaient',
    'يَلْبَثُوٓا۟': 'demeuré sur terre',
    'عَشِيَّةً': 'qu’une fin d’après-midi',
    'أَوْ': 'ou',
    'ضُحَىٰهَا': 'sa matinée naissante',

    # Surah 80 Abasa
    'عَبَسَ': 'Il a froncé les sourcils',
    'جَآءَهُ': 'est venu à lui (chercher conseil)',
    'يُدْرِيكَ': 'te fera savoir / te dit',
    'يَزَّكَّىٰٓ': 'se purifier de ses péchés ?',
    'يَذَّكَّرُ': 'se rappeler et tirer profit du rappel ?',
    'أَمَّا': 'quant à',
    'ٱسْتَغْنَىٰ': 'se croit autosuffisant par son orgueil',
    'تَصَدَّىٰ': 'tu t’empresses auprès de lui',
    'عَلَيْكَ': 'sur toi / à ta charge',
    'أَلَّا': 'qu’il ne... point',
    'يَزَّكَّىٰ': 'se purifie',
    'جَآءَكَ': 'est venu à toi avec empressement',
    'عَنْهُ': 'de lui / à son égard',
    'تَلَهَّىٰ': 'tu te laisses distraire',
    'إِنَّهَا': 'en vérité cette révélation',
    'تَذْكِرَةٌ': 'est un rappel solennel',
    'ذَكَرَهُۥ': 's’en rappelle et médite',
    'صُحُفٍ': 'des feuillets et pages',
    'مُّكَرَّمَةٍ': 'vénérés et hautement honorés',
    'مَّرْفُوعَةٍ': 'sublimes et élevées en rang',
    'مُّطَهَّرَةٍۭ': 'purifiées de toute souillure',
    'بِأَيْدِى': 'portés par les mains de',
    'سَفَرَةٍ': 'scribes angéliques nobles',
    'كِرَامٍۭ': 'nobles et dévoués',
    'بَرَرَةٍ': 'obéissants et vertueux',
    'قُتِلَ': 'que périsse maudit',
    'مَآ': 'combien / que',
    'أَكْفَرَهُۥ': 'il est ingrat envers son Créateur !',
    'أَىِّ': 'à partir de quelle',
    'شَىْءٍ': 'matière / chose',
    'خَلَقَهُۥ': 'l’a-t-Il donc créé ?',
    'نُّطْفَةٍ': 'd’une goutte de fluide séminal',
    'فَقَدَّرَهُۥ': 'puis l’a façonné avec mesure',
    'ٱلسَّبِيلَ': 'le chemin de la naissance et de la vie',
    'يَسَّرَهُۥ': 'Il le lui a rendu aisé',
    'أَمَاتَهُۥ': 'Il lui a fait donner la mort',
    'فَأَقْبَرَهُۥ': 'puis l’a fait ensevelir dans la tombe',
    'شَآءَ': 'Il le voudra',
    'أَنشَرَهُۥ': 'Il le ressuscitera d’entre les morts',
    'لَمَّا': 'il n’a pas encore',
    'يَقْضِ': 'accompli et acquitté',
    'أَمَرَهُۥ': 'ce qu’Il lui avait formellement ordonné',
    'فَلْيَنظُرِ': 'qu’il observe donc et médite',
    'طَعَامِهِۦٓ': 'sa nourriture quotidienne',
    'صَبَبْنَا': 'Nous avons versé en abondance',
    'صَبًّا': 'à verse et à flots',
    'شَقَقْنَا': 'Nous avons fendu',
    'شَقًّا': 'par des sillons réguliers',
    'فَأَنۢبَتْنَا': 'et Nous y avons fait germer',
    'حَبًّا': 'des grains et céréales nourricières',
    'وَعِنَبًا': 'des vignes opulentes',
    'وَقَضْبًا': 'et du fourrage succulent pour bétail',
    'وَزَيْتُونًا': 'des oliviers bénis',
    'وَنَخْلًا': 'des palmiers dattiers',
    'وَحَدَآئِقَ': 'des vergers luxuriants',
    'غُلْبًا': 'aux arbres hauts et touffus',
    'وَفَـٰكِهَةً': 'des fruits savoureux',
    'وَأَبًّا': 'et des herbages fertiles',
    'جَآءَتِ': 'retentira soudain',
    'ٱلصَّـٰٓخَّةُ': 'le Fracas assourdissant de la Résurrection',
    'يَفِرُّ': 's’enfuira éperdu',
    'ٱلْمَرْءُ': 'l’homme angoissé',
    'أَخِيهِ': 'son propre frère',
    'وَأُمِّهِۦ': 'sa mère bien-aimée',
    'وَأَبِيهِ': 'son père respecté',
    'وَصَـٰحِبَتِهِۦ': 'sa compagne de vie',
    'وَبَنِيهِ': 'ses propres enfants chéris',
    'لِكُلِّ': 'à chaque',
    'ٱمْرِئٍ': 'être humain',
    'شَأْنٌ': 'une préoccupation majeure',
    'يُغْنِيهِ': 'qui absorbera toute son attention',
    'وُجُوهٌ': 'des visages',
    'مُّسْفِرَةٌ': 'rayonnants de joie et lumineux',
    'ضَاحِكَةٌ': 'riants d’allégresse',
    'مُّسْتَبْشِرَةٌ': 'réjouis de la bonne nouvelle',
    'عَلَيْهَا': 'recouverts de',
    'غَبَرَةٌ': 'poussière de honte et d’effroi',
    'تَرْهَقُهَا': 'les enveloppera',
    'قَتَرَةٌ': 'une noirceur ténébreuse et sinistre',
    'أُو۟لَـٰٓئِكَ': 'ceux-là précisément',
    'هُمُ': 'sont eux',
    'ٱلْكَفَرَةُ': 'les mécréants obstinés',
    'ٱلْفَجَرَةُ': 'les pervers impudents',
}
