# scripts/lexicon_data_part2.py
# Comprehensive, accurate French translations for Quranic vocabulary in Juz 'Amma (Surahs 81 to 87)

LEXICON_PART2 = {
    # Surah 81 At-Takwir
    'كُوِّرَتْ': 'sera enroulé et obscurci (le soleil)',
    'ٱنكَدَرَتْ': 'perdront leur éclat et chuteront',
    'سُيِّرَتْ': 'seront pulvérisées en poussière errante',
    'عُطِّلَتْ': 'seront laissées à l’abandon sans gardien',
    'حُشِرَتْ': 'seront rassemblés en foule affolée',
    'سُجِّرَتْ': 'seront embrasées et transformées en feu',
    'زُوِّجَتْ': 'seront réunies à leurs semblables',
    'ٱلْمَوْءُۥدَةُ': 'la fillette enterrée vivante',
    'سُئِلَتْ': 'sera interrogée avec justice',
    'بِأَىِّ': 'pour quel',
    'ذَنۢبٍ': 'crime odieux',
    'نُشِرَتْ': 'seront déployés pour le jugement',
    'كُشِطَتْ': 'sera arraché et découplé',
    'سُعِّرَتْ': 'sera attisée d’une chaleur furieuse',
    'أُزْلِفَتْ': 'sera rapprochée des croyants pieux',
    'عَلِمَتْ': 'saura avec une certitude absolue',
    'أَحْضَرَتْ': 'ce qu’elle a présenté comme œuvres',
    'فَلَآ': 'Non ! Mais',
    'أُقْسِمُ': 'Je prends à témoin / Je jure par',
    'بِٱلْخُنَّسِ': 'les astres qui reculent et se dérobent',
    'ٱلْجَوَارِ': 'qui voguent sur leurs orbites',
    'ٱلْكُنَّسِ': 'et disparaissent dans leurs refuges',
    'عَسْعَسَ': 'quand elle commence à se dissiper',
    'تَنَفَّسَ': 'quand il exhale ses premières lueurs',
    'لَقَوْلُ': 'est assurément la parole transmise par',
    'رَسُولٍ': 'un noble émissaire angélique (Jibril)',
    'كَرِيمٍ': 'noble et digne de vénération',
    'ذِى': 'doté de',
    'قُوَّةٍ': 'force et puissance souveraine',
    'عِندَ': 'auprès du',
    'ٱلْعَرْشِ': 'Trône suprême',
    'مَكِينٍ': 'établi en un rang éminent',
    'مُّطَاعٍ': 'obéi par l’assemblée angélique',
    'ثَمَّ': 'là-haut',
    'أَمِينٍ': 'loyal et digne d’une confiance totale',
    'صَاحِبُكُم': 'votre compagnon (Muhammad)',
    'بِمَجْنُونٍ': 'possédé d’aucune folie',
    'رَءَاهُ': 'il l’a contemplé de ses yeux',
    'بِٱلْأُفُقِ': 'à l’horizon céleste',
    'ٱلْمُبِينِ': 'inondé d’une lumière éclatante',
    'ٱلْغَيْبِ': 'l’Inconnaissable et la Révélation',
    'بِضَنِينٍ': 'avare ni soupçonné de dissimulation',
    'بِقَوْلِ': 'la parole insidieuse de',
    'شَيْطَـٰنٍ': 'démon insidieux',
    'رَّجِيمٍ': 'lapidé et maudit',
    'فَأَيْنَ': 'vers où donc',
    'تَذْهَبُونَ': 'vous égarez-vous ainsi ?',
    'ذِكْرٌ': 'un rappel solennel',
    'لِّلْعَـٰلَمِينَ': 'pour l’humanité et tous les univers',
    'لِمَن': 'pour quiconque parmi vous',
    'يَسْتَقِيمَ': 'se tenir droit sur la voie de droiture',
    'تَشَآءُونَ': 'vous ne pouvez vouloir',
    'يَشَآءَ': 'que ce que veuille',

    # Surah 82 Al-Infitar
    'ٱنفَطَرَتْ': 'se fendra et se déchirera',
    'ٱنتَثَرَتْ': 'se disperseront et chuteront',
    'فُجِّرَتْ': 'déborderont et fusionneront',
    'بُعْثِرَتْ': 'seront retournées et bouleversées',
    'قَدَّمَتْ': 'ce qu’elle a avancé comme actes',
    'وَأَخَّرَتْ': 'et ce qu’elle a différé ou négligé',
    'يَـٰٓأَيُّهَا': 'Ô',
    'ٱلْإِنسَـٰنُ': 'être humain !',
    'غَرَّكَ': 't’a donc trompé et illusionné ?',
    'بِرَبِّكَ': 'au sujet de ton Seigneur',
    'ٱلْكَرِيمِ': 'le Généreux et Bienveillant',
    'خَلَقَكَ': 't’a créé de rien',
    'فَسَوَّىٰكَ': 't’a donné une conformation harmonieuse',
    'فَعَدَلَكَ': 'et t’a équilibré à la perfection',
    'فِىٓ': 'en',
    'صُورَةٍ': 'forme admirable',
    'رَّكَّبَكَ': 'Il t’a agencé et façonné',
    'تُكَذِّبُونَ': 'vous mentez effrontément sur',
    'بِٱلدِّينِ': 'la Rétribution et le Jugement',
    'عَلَيْكُمْ': 'veillant sur vous',
    'لَحَـٰفِظِينَ': 'des gardiens angéliques vigilants',
    'كِرَامًا': 'nobles et scrupuleux',
    'كَـٰتِبِينَ': 'consignant fidèlement par écrit',
    'يَعْلَمُونَ': 'qui savent parfaitement',
    'تَفْعَلُونَ': 'tout ce que vous faites',
    'ٱلْأَبْرَارَ': 'les pieux et sincères croyants',
    'نَعِيمٍ': 'délices perpétuels et félicité',
    'ٱلْفُجَّارَ': 'les pervers et désobéissants',
    'جَحِيمٍ': 'un Feu ardent et suffocant',
    'يَصْلَوْنَهَا': 'ils y brûleront et endureront',
    'يَوْمَ': 'au Jour de',
    'عَنْهَا': 'de ce châtiment',
    'بِغَآئِبِينَ': 'capables d’en échapper un seul instant',
    'أَدْرَىٰكَ': 'te fera mesurer la portée de',
    'ثُمَّ': 'Puis',
    'تَمْلِكُ': 'ne possédera le moindre pouvoir',
    'نَفْسٌ': 'une âme',
    'لِّنَفْسٍ': 'en faveur d’une autre âme',
    'شَيْـًٔا': 'la moindre parcelle de secours',
    'وَٱلْأَمْرُ': 'et l’autorité souveraine absolue',
    'لِلَّهِ': 'appartiendra à Allah seul',

    # Surah 83 Al-Mutaffifin
    'وَيْلٌ': 'Malheur suprême et ruine',
    'لِّلْمُطَفِّفِينَ': 'aux fraudeurs qui tronquent les mesures',
    'ٱكْتَالُوا۟': 'ils se font mesurer par autrui',
    'عَلَى': 'auprès de',
    'ٱلنَّاسِ': 'des gens',
    'يَسْتَوْفُونَ': 'ils exigent leur pleine mesure avec rigueur',
    'كَالُوهُمْ': 'ils mesurent pour autrui',
    'وَّزَنُوهُمْ': 'ou pèsent sur la balance pour autrui',
    'يُخْسِرُونَ': 'ils causent un préjudice en trichant',
    'أَلَا': 'Ne se doutent-ils pas donc ?',
    'يَظُنُّ': 'pensent-ils avec sérieux ?',
    'مَّبْعُوثُونَ': 'seront ressuscités d’entre les morts',
    'لِيَوْمٍ': 'pour comparaître en un Jour',
    'عَظِيمٍ': 'redoutable et grandiose',
    'يَقُومُ': 'se tiendra debout',
    'لِرَبِّ': 'devant le Seigneur',
    'كِتَـٰبَ': 'le registre des actions de',
    'سِجِّينٍ': 'Sijjîn (abîme ténébreux de réclusion)',
    'وَمَآ': 'Et que',
    'مَّرْقُومٌ': 'scellé, indélébile et chiffré',
    'لِّلْمُكَذِّبِينَ': 'à ceux qui démentent avec cynisme',
    'يُكَذِّبُ': 'ne dément cette vérité que',
    'مُعْتَدٍ': 'un transgresseur arrogant',
    'أَثِيمٍ': 'enraciné dans le péché',
    'تُتْلَىٰ': 'sont récités avec clarté',
    'ءَايَـٰتُنَا': 'Nos versets lumineux',
    'أَسَـٰطِيرُ': 'des contes et fables imaginaires',
    'ٱلْأَوَّلِينَ': 'des peuples anciens d’autrefois',
    'بَلْ': 'Bien au contraire ! Mais',
    'رَانَ': 'a rouillé et encroûté',
    'قُلُوبِهِم': 'leurs cœurs aveuglés',
    'كَانُوا۟': 'ils s’étaient habitués à',
    'يَكْسِبُونَ': 'commettre comme méfaits',
    'رَّبِّهِمْ': 'la contemplation de leur Seigneur',
    'مَّحْجُوبُونَ': 'seront impitoyablement privés par un voile',
    'لَصَالُوا۟': 'brûleront sans répit dans',
    'ٱلَّذِى': 'que',
    'كُنتُم': 'vous aviez l’habitude de',
    'عِلِّيِّينَ': '’Illiyyîn (les hautes cimes célestes)',
    'يَشْهَدُهُ': 'en attestent et le contemplent',
    'ٱلْمُقَرَّبُونَ': 'les anges et élus les plus rapprochés',
    'ٱلْأَرَآئِكِ': 'des divans royaux ornés',
    'يَنظُرُونَ': 'ils contemplent les délices infinis',
    'تَعْرِفُ': 'tu discerneras aussitôt sur',
    'وُجُوهِهِمْ': 'leurs visages resplendissants',
    'نَضْرَةَ': 'l’éclatante fraîcheur de',
    'ٱلنَّعِيمِ': 'la félicité céleste',
    'يُسْقَوْنَ': 'on leur servira à boire',
    'رَّحِيقٍ': 'd’un nectar divin d’une pureté absolue',
    'مَّخْتُومٍ': 'scellé de cachets inviolés',
    'خِتَـٰمُهُۥ': 'dont le sillage ultime exhale',
    'مِسْكٌ': 'un musc raffiné incomparable',
    'فَلْيَتَنَافَسِ': 'que rivalisent avec ardeur',
    'ٱلْمُتَنَـٰفِسُونَ': 'ceux qui cherchent la noble excellence',
    'مِزَاجُهُۥ': 'sa composition subtile provient',
    'تَسْنِيمٍ': 'de Tasnîm (la plus noble source du Paradis)',
    'عَيْنًا': 'une source limpide',
    'يَشْرَبُ': 'à laquelle boivent',
    'بِهَا': 'délicieusement',
    'أَجْرَمُوا۟': 'commettaient des crimes odieux',
    'ءَامَنُوا۟': 'ont sincèrement cru',
    'يَضْحَكُونَ': 'se moquaient d’eux avec dédain',
    'مَرُّوا۟': 'passaient à proximité',
    'يَتَغَامَزُونَ': 'se faisaient des clins d’œil moqueurs',
    'ٱنقَلَبُوٓا۟': 'ils retournaient satisfaits',
    'أَهْلِهِمُ': 'leurs familles complices',
    'فَكِهِينَ': 'badinant et ricanant d’ironie',
    'رَأَوْهُمْ': 'ils les apercevaient au loin',
    'ضَآلُّونَ': 'sont complètement égarés !',
    'أُرْسِلُوا۟': 'ils n’avaient nullement été envoyés',
    'حَـٰفِظِينَ': 'comme gardiens et censeurs sur eux',
    'فَٱلْيَوْمَ': 'Mais en ce Jour solennel',
    'ٱلْكُفَّارِ': 'des mécréants autrefois arrogants',
    'هَلْ': 'n’ont-ils pas reçu ?',
    'ثُوِّبَ': 'en exacte récompense',
    'ٱلْكُفَّارُ': 'les négateurs infatués',
    'يَفْعَلُونَ': 'ce qu’ils faisaient jadis ?',

    # Surah 84 Al-Inchiqaq & Surah 85 Al-Buruj & 86 & 87
    'ٱنشَقَّتْ': 'se fendra et se déchirera sous l’ordre',
    'أَذِنَتْ': 'obéira avec soumission totale à',
    'حُقَّتْ': 'il lui incombe de plein droit d’obéir',
    'مُدَّتْ': 'sera aplanie et étendue à perte de vue',
    'أَلْقَتْ': 'rejettera ce qu’elle renfermait',
    'تَخَلَّتْ': 'et se videra de tout son contenu',
    'كَادِحٌ': 'avançant dans un labeur incessant',
    'كَدْحًا': 'un effort soutenu et persistant',
    'فَمُلَـٰقِيهِ': 'tu en contempleras le résultat devant Lui',
    'أُوتِىَ': 'recevra la remise de',
    'بِيَمِينِهِۦ': 'dans sa main droite bénie',
    'يُحَاسَبُ': 'sera soumis à reddition de comptes',
    'حِسَابًا': 'un examen de comptes',
    'يَسِيرًا': 'bienveillant, rapide et aisé',
    'يَنقَلِبُ': 'il retournera rayonnant vers',
    'مَسْرُورًا': 'comblé d’allégresse et de joie',
    'وَرَآءَ': 'par-derrière',
    'ظَهْرِهِۦ': 'son dos honteux',
    'يَدْعُوا۟': 'il appellera à grands cris',
    'ثُبُورًا': 'sa propre destruction et anéantissement',
    'يَصْلَىٰ': 'il brûlera vif dans',
    'سَعِيرًا': 'un brasier infernal attisé',
    'ظَنَّ': 's’imaginait follement',
    'لَّن': 'qu’il ne... jamais',
    'يَحُورَ': 'retournerait à la vie devant Dieu',
    'بَصِيرًا': 'parfaitement Clairvoyant sur ses actes',
    'بِٱلشَّفَقِ': 'par le crépuscule rougeoyant',
    'وَٱلَّيْلِ': 'par la nuit enveloppante',
    'وَسَقَ': 'ce qu’elle rassemble dans son ombre',
    'وَٱلْقَمَرِ': 'par la lune resplendissante',
    'ٱتَّسَقَ': 'quand elle devient pleine et éclatante',
    'لَتَرْكَبُنَّ': 'vous franchirez immanquablement',
    'طَبَقًا': 'des étapes successives majeures',
    'عَن': 'après',
    'طَبَقٍ': 'étape de l’existence',
    'قُرِئَ': 'leur est déclamé solennellement',
    'ٱلْقُرْءَانُ': 'le sublime Coran',
    'يَسْجُدُونَ': 'ils ne se prosternent avec humilité',
    'أَعْلَمُ': 'sait parfaitement',
    'يُوعُونَ': 'ce qu’ils dissimulent en leurs cœurs',
    'فَبَشِّرْهُم': 'annonce-leur donc la venue de',
    'بِعَذَابٍ': 'un tourment atroce et pénible',
    'أَلِيمٍ': 'douloureux et terrifiant',
    'أَجْرٌ': 'une rétribution magnifique',
    'غَيْرُ': 'qui ne sera jamais',
    'مَمْنُونٍۭ': 'interrompue ni diminuée',

    # Surah 85 Al-Buruj
    'ذَاتِ': 'doté de / pourvue de',
    'ٱلْبُرُوجِ': 'constellations géantes étincelantes',
    'ٱلْمَوْعُودِ': 'solennellement promis et fixé',
    'وَشَاهِدٍ': 'par le témoin oculaire véridique',
    'وَمَشْهُودٍ': 'et le grand jour dont on témoignera',
    'أَصْحَـٰبُ': 'les tortionnaires criminels de',
    'ٱلْأُخْدُودِ': 'la tranchée creusée du brasier',
    'ٱلنَّارِ': 'du feu avide de chair',
    'ٱلْوَقُودِ': 'attisé par un abondant combustible',
    'قُعُودٌ': 'assis tout autour avec cruauté',
    'شُهُودٌ': 'témoins impassibles du massacre',
    'نَقَمُوا۟': 'ils ne leur reprochaient aucun grief',
    'ٱلْعَزِيزِ': 'le Tout-Puissant invulnérable',
    'ٱلْحَمِيدِ': 'le Digne de louanges infinies',
    'مُلْكُ': 'la royauté et domination absolue de',
    'ٱلسَّمَـٰوَٰتِ': 'des cieux majestueux',
    'وَٱلْأَرْضِ': 'et de la terre',
    'شَهِيدٌ': 'Témoin omniscient de tout acte',
    'فَتَنُوا۟': 'ont persécuté et torturé',
    'ٱلْمُؤْمِنِينَ': 'les hommes croyants',
    'ٱلْمُؤْمِنَـٰتِ': 'et les femmes croyantes',
    'يَتُوبُوا۟': 'ils ne se sont point repentis',
    'عَذَابُ': 'le châtiment implacable de',
    'ٱلْحَرِيقِ': 'l’Embrasement et de la crémation',
    'جَنَّـٰتٌ': 'des Jardins d’éden parfaits',
    'تَجْرِى': 'sous lesquels s’écoulent',
    'تَحْتِهَا': 'à leurs pieds',
    'ٱلْأَنْهَـٰرُ': 'des ruisseaux d’eaux pures',
    'ٱلْفَوْزُ': 'le triomphe et accomplissement',
    'ٱلْكَبِيرُ': 'suprême et sans égal',
    'بَطْشَ': 'la riposte et la saisie de',
    'لَشَدِيدٌ': 'est d’une rigueur redoutable',
    'يُبْدِئُ': 'initie la création première',
    'يُعِيدُ': 'et la recrée à nouveau au Jugement',
    'ٱلْغَفُورُ': 'le Pardonneur par excellence',
    'ٱلْوَدُودُ': 'l’Aimant empli de tendresse pure',
    'ٱلْمَجِيدُ': 'le Glorieux et Majestueux',
    'فَعَّالٌ': 'Il accomplit souverainement',
    'يُرِيدُ': 'ce qu’Il décide et veut',
    'جُنُودِ': 'les armées rebelles d’antan',
    'فِرْعَوْنَ': 'de Pharaon l’insolent tyran',
    'وَثَمُودَ': 'et du peuple orgueilleux de Thamûd',
    'تَكْذِيبٍ': 'démenti perpétuel de l’évidence',
    'وَّرَآئِهِم': 'les cernant de toute part',
    'مُّحِيطٌۢ': 'embrasse tout de Sa science',
    'مَّجِيدٌ': 'sublime et préservé de toute altération',
    'لَّوْحٍ': 'une Table inviolable',
    'مَّحْفُوظٍۭ': 'conservée au plus haut des cieux',

    # Surah 86 At-Tariq & 87 Al-A'la
    'وَٱلطَّارِقِ': 'par l’Astre nocturne perçant l’obscurité',
    'ٱلنَّجْمُ': 'l’astre céleste fulgurant',
    'ٱلثَّاقِبُ': 'dont la lueur transperce l’ombre',
    'عَلَيْهَا': 'veillant attentivement sur elle',
    'حَافِظٌ': 'un gardien céleste protecteur',
    'فَلْيَنظُرِ': 'que l’être humain médite donc',
    'مِمَّ': 'à partir de quoi',
    'خُلِقَ': 'il a été façonné et créé',
    'مَّآءٍ': 'd’un fluide jaillissant',
    'دَافِقٍ': 'éjecté avec impulsion vitale',
    'يَخْرُجُ': 'qui émane de la zone vitale',
    'بَيْنِ': 'située entre',
    'ٱلصُّلْبِ': 'l’épine dorsale',
    'وَٱلتَّرَآئِبِ': 'et la cage thoracique',
    'رَجْعِهِۦ': 'le ressusciter à la vie',
    'لَقَادِرٌ': 'est assurément Tout-Puissant',
    'تُبْلَى': 'seront dévoilés et mis à nu',
    'ٱلسَّرَآئِرُ': 'les secrets les plus intimes des cœurs',
    'قُوَّةٍ': 'la moindre force autonome',
    'نَاصِرٍ': 'ni aucun allié pour le défendre',
    'ٱلرَّجْعِ': 'aux pluies régulières et cycliques',
    'ٱلصَّدْعِ': 'qui se fissure pour laisser germer la vie',
    'فَصْلٌ': 'une parole décisive qui tranche',
    'بِٱلْهَزْلِ': 'une parole futile ou légère',
    'يَكِيدُونَ': 'ils trament des ruses tortueuses',
    'كَيْدًا': 'un complot pernicieux',
    'وَأَكِيدُ': 'et Je déploie Ma sage riposte',
    'فَمَهِّلِ': 'accorde donc un répit bienveillant',
    'أَمْهِلْهُمْ': 'laisse-leur un court délai',
    'رُوَيْدًۢا': 'très bref avant la rétribution',

    # Surah 87 Al-A'la
    'سَبِّحِ': 'Glorifie et sanctifie avec ferveur',
    'ٱسْمَ': 'le Nom sacré de',
    'ٱلْأَعْلَى': 'le Très-Haut, suprême au-dessus de tout',
    'فَسَوَّىٰ': 'et l’a parachevé avec proportion',
    'قَدَّرَ': 'a déterminé les destinées et capacités',
    'فَهَدَىٰ': 'puis a guidé chaque être vers sa voie',
    'ٱلْمَرْعَىٰ': 'le pâturage verdoyant et luxuriant',
    'فَجَعَلَهُۥ': 'puis l’a transformé ensuite',
    'غُثَآءً': 'en foin desséché et débris flottants',
    'أَحْوَىٰ': 'devenu sombre et noirci par le temps',
    'سَنُقْرِئُكَ': 'Nous te ferons réciter la Révélation',
    'فَلَا': 'de sorte que tu n’en',
    'تَنسَىٰٓ': 'oublieras pas la moindre lettre',
    'ٱلْجَهْرَ': 'ce qui est proclamé à voix haute',
    'يَخْفَىٰ': 'ce qui reste dissimulé au fond des cœurs',
    'وَنُيَسِّرُكَ': 'et Nous te faciliterons l’accès',
    'لِلْيُسْرَىٰ': 'à la voie la plus douce et bienfaisante',
    'فَذَكِّرْ': 'rappelle donc inlassablement',
    'نَّفَعَتِ': 'si le rappel s’avère profitable',
    'ٱلذِّكْرَىٰ': 'le Rappel et l’avertissement',
    'سَيَذَّكَّرُ': 'en tirera profit avec piété',
    'وَيَتَجَنَّبُهَا': 'mais s’en détournera avec mépris',
    'ٱلْأَشْقَى': 'le plus misérable et endurci',
    'ٱلْكُبْرَىٰ': 'le Suprême et gigantesque',
    'يَمُوتُ': 'il ne trouvera la mort pour abréger sa peine',
    'يَحْيَىٰ': 'ni ne connaîtra une vie apaisée',
    'أَفْلَحَ': 'a certes triomphé et trouvé le salut',
    'تَزَكَّىٰ': 'quiconque s’est purifié des souillures',
    'فَصَلَّىٰ': 'et a accompli la prière avec dévotion',
    'تُؤْثِرُونَ': 'vous accordez une préférence aveugle à',
    'خَيْرٌ': 'infiniment meilleure et plus digne',
    'وَأَبْقَىٰٓ': 'et infiniment plus durable et éternelle',
    'ٱلصُّحُفِ': 'les Écritures et Feuillets révélés',
    'ٱلْأُولَىٰ': 'aux premières nations de jadis',
    'صُحُفِ': 'les Feuillets sacrés accordés à',
    'إِبْرَٰهِيمَ': 'Abraham (Ibrahim)',
}
